'use client';
import SiteNav from '@/components/SiteNav';
import SiteFooter from '@/components/SiteFooter';
import { useReveal } from '@/hooks/useReveal';

const SECTIONS = [
    {
        id: 'information-we-collect',
        title: '1. Information We Collect',
        color: '#6b96ff',
        content: [
            {
                subtitle: 'Account Information',
                text: 'When you create a Flowcent account, we collect your name, email address and optional company name. Supabase Auth receives and processes your password; Flowcent does not store a plain-text password in its application database.',
            },
            {
                subtitle: 'Invoice & Client Data',
                text: 'We store invoice details (client names, amounts, due dates, payment status) and client contact information (email addresses, phone numbers, company names) that you enter into the platform.',
            },
            {
                subtitle: 'Gmail Integration Data',
                text: 'When you connect Gmail via OAuth, encrypted access credentials are stored so Flowcent can send follow-up emails on your behalf. Flowcent requests Gmail send access and account email identity, not inbox-read access. Sent template content and delivery records may be retained with the invoice.',
            },
            {
                subtitle: 'Operational Records',
                text: 'The application stores usage counters needed for plan limits, payment webhook records, follow-up delivery records, and security or error logs generated by the application and hosting providers. Processed webhook payloads are scheduled for deletion after 90 days. Flowcent does not configure advertising trackers in this app.',
            },
        ],
    },
    {
        id: 'how-we-use-your-data',
        title: '2. How We Use Your Data',
        color: '#a78bfa',
        content: [
            {
                subtitle: 'Core Product Functionality',
                text: 'Your data is used to operate and secure Flowcent, including invoice tracking, follow-up delivery, payment verification, plan enforcement, support, account export and deletion.',
            },
            {
                subtitle: 'AI Features',
                text: 'When you use AI features, invoice context and client reply text may be sent to the configured AI provider to generate an analysis. Provider handling is governed by its terms and the deployment configuration.',
            },
            {
                subtitle: 'Service Emails',
                text: 'Authentication providers may send transactional account confirmation and password reset emails. Payment providers may issue their own payment confirmations under their policies.',
            },
        ],
    },
    {
        id: 'data-storage-security',
        title: '3. Data Storage & Security',
        color: '#34d399',
        content: [
            {
                subtitle: 'Infrastructure',
                text: 'Application data is stored in the configured Supabase project and processed by the configured hosting and provider infrastructure. Deployment region, backup retention and transport or storage protections follow those provider settings and contracts.',
            },
            {
                subtitle: 'Authentication',
                text: 'Supabase Auth manages password hashing, session tokens, email confirmation and password reset. Session lifetime and authentication controls depend on the production Supabase project configuration.',
            },
            {
                subtitle: 'Access Controls',
                text: 'The production database must apply Flowcent\'s Row Level Security policies and API-only write grants so authenticated users can access only records associated with their account.',
            },
        ],
    },
    {
        id: 'data-sharing',
        title: '4. Data Sharing & Third Parties',
        color: '#fbbf24',
        content: [
            {
                subtitle: 'We Never Sell Your Data',
                text: 'We do not sell, rent, or trade your personal information to any third party, ever.',
            },
            {
                subtitle: 'Service Providers',
                text: 'Data is shared only as needed with configured service providers such as Supabase, the deployment host, Google Gmail, Gemini or Groq, Razorpay, Stripe, and optional WhatsApp Cloud API. Each provider processes data under its own applicable terms and deployment configuration.',
            },
            {
                subtitle: 'Legal Requirements',
                text: 'We may disclose data when required by Indian law, a court order, or to protect the rights and safety of our users and the public.',
            },
        ],
    },
    {
        id: 'your-rights',
        title: '5. Your Rights',
        color: '#f87171',
        content: [
            {
                subtitle: 'Data Access & Export',
                text: 'Authenticated users can download a machine-readable account export from Settings. You may contact theravission@gmail.com if the in-product export is unavailable.',
            },
            {
                subtitle: 'Account Deletion',
                text: 'You may delete your account from Settings after confirming your email. Active application records are removed through the account deletion workflow; residual provider backups and security logs may remain for their configured retention periods or legal requirements.',
            },
            {
                subtitle: 'Data Correction',
                text: 'If any personal data we hold is inaccurate, you may update it directly in your account settings or contact us.',
            },
        ],
    },
    {
        id: 'cookies',
        title: '6. Cookies',
        color: '#06b6d4',
        content: [
            {
                subtitle: 'Essential Cookies',
                text: 'Flowcent uses essential cookies for Supabase session authentication and OAuth security state. This app does not configure advertising cookies.',
            },
        ],
    },
    {
        id: 'changes',
        title: '7. Changes to This Policy',
        color: '#a78bfa',
        content: [
            {
                subtitle: '',
                text: 'We may update this Privacy Policy periodically. Material changes will be notified to you via email at least 14 days before they take effect. Continued use of Flowcent after changes constitutes acceptance.',
            },
        ],
    },
];

export default function PrivacyPage() {
    useReveal();

    return (
        <div className="min-h-screen bg-[#09090f] text-white overflow-x-hidden">
            {/* Background */}
            <div className="fixed inset-0 pointer-events-none overflow-hidden">
                <div className="aurora-blob aurora-blob-blue w-[600px] h-[600px]"
                    style={{ top: '-100px', left: '20%', opacity: 0.15 }} />
                <div className="aurora-blob aurora-blob-purple w-[400px] h-[400px]"
                    style={{ bottom: '20%', right: '-5%', opacity: 0.12 }} />
                <div className="absolute inset-0 grid-bg opacity-15" />
            </div>

            <SiteNav />

            {/* Hero */}
            <section className="relative z-10 pt-32 pb-16 px-6 text-center">
                <div className="max-w-3xl mx-auto reveal-up">
                    <span className="text-xs font-semibold tracking-[0.2em] text-blue-400 uppercase mb-4 block">Legal</span>
                    <h1 className="text-4xl sm:text-5xl font-bold mb-5 tracking-tight">
                        Privacy <span className="grad-text">Policy</span>
                    </h1>
                    <p className="text-white/50 text-lg max-w-xl mx-auto">
                        We believe your data belongs to you. Here's exactly how we handle it.
                    </p>
                    <div className="flex items-center justify-center gap-3 mt-6 text-xs text-white/30">
                        <span>Last updated: June 23, 2026</span>
                        <span>·</span>
                        <span>Effective from June 23, 2026</span>
                    </div>
                </div>
            </section>

            {/* Table of Contents */}
            <section className="relative z-10 px-6 pb-10 reveal-up reveal-delay-2">
                <div className="max-w-3xl mx-auto glass-card p-6 rounded-2xl">
                    <p className="text-xs font-bold text-white/30 uppercase tracking-widest mb-4">Table of Contents</p>
                    <ol className="space-y-2">
                        {SECTIONS.map((s) => (
                            <li key={s.id}>
                                <a href={`#${s.id}`}
                                    className="text-sm text-white/50 hover:text-white transition-colors flex items-center gap-2">
                                    <span style={{ color: s.color }} className="text-xs">●</span>
                                    {s.title}
                                </a>
                            </li>
                        ))}
                    </ol>
                </div>
            </section>

            {/* Sections */}
            <section className="relative z-10 px-6 pb-20">
                <div className="max-w-3xl mx-auto space-y-8">
                    {SECTIONS.map((section, si) => (
                        <div key={section.id} id={section.id}
                            className={`reveal-up reveal-delay-${Math.min(si + 1, 6)}`}>
                            <div className="glass-card rounded-2xl p-8 border"
                                style={{ borderColor: `${section.color}20` }}>
                                <h2 className="text-xl font-bold mb-6 flex items-center gap-3">
                                    <span className="w-2 h-6 rounded-full inline-block shrink-0"
                                        style={{ background: section.color }} />
                                    {section.title}
                                </h2>
                                <div className="space-y-5">
                                    {section.content.map((item, ci) => (
                                        <div key={ci}>
                                            {item.subtitle && (
                                                <h3 className="text-sm font-semibold text-white/80 mb-1.5"
                                                    style={{ color: `${section.color}cc` }}>
                                                    {item.subtitle}
                                                </h3>
                                            )}
                                            <p className="text-sm text-white/50 leading-relaxed">{item.text}</p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    ))}

                    {/* Contact */}
                    <div className="reveal-up glass-card rounded-2xl p-8 border border-blue-500/20 text-center">
                        <p className="text-white/50 text-sm mb-3">Questions about this policy?</p>
                        <a href="mailto:theravission@gmail.com"
                            className="text-blue-400 hover:text-blue-300 font-medium transition-colors">
                            theravission@gmail.com
                        </a>
                        <p className="text-xs text-white/25 mt-4">
                            Flowcent Technologies · India
                        </p>
                    </div>
                </div>
            </section>

            <SiteFooter />
        </div>
    );
}
